Repository cortip/isomera, pull requests merged in 2022-11, with the labels that each got.

#49 #48 added code contributors list on the main website; added library f…
  apps/website/components/Contributors/Contributors.component.tsx
  apps/website/next.config.js
  apps/website/pages/404.tsx
  apps/website/pages/index.tsx
  libs/interfaces/.babelrc
  libs/interfaces/.eslintrc.json
  libs/interfaces/README.md
  libs/interfaces/jest.config.ts
  libs/interfaces/project.json
  libs/interfaces/src/index.ts
  libs/interfaces/src/lib/github/GithubContributor.interface.ts
  libs/interfaces/src/lib/interfaces.spec.tsx
  libs/interfaces/src/lib/interfaces.tsx
  libs/interfaces/tsconfig.json
  libs/interfaces/tsconfig.lib.json
  libs/interfaces/tsconfig.spec.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: enhancement

#53 #52 added husky prepare script and pre-commit
  .husky/pre-commit
  package.json
Labels: enhancement

#51 #50 added docker-compose and Docker for Postgresql and Redis; updated…
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#55 #54 added pull request template and bug report template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#59 #58 rebuild whole website
  .github/workflows/commit_e2e.yml
  apps/dashboard-e2e/project.json
  apps/website-e2e/src/e2e/app.cy.ts
  apps/website/.babelrc
  apps/website/assets/Asset 3.svg
  apps/website/assets/illustrtation1.svg
  apps/website/components/Contributors/Contributors.component.tsx
  apps/website/components/Hero/HomepageHero.component.tsx
  apps/website/components/TopNavigation/TopNavigation.component.tsx
  apps/website/components/globalstyles.tsx
  apps/website/components/layout/container.tsx
  apps/website/config/theme.ts
  apps/website/next.config.js
  apps/website/pages/404.tsx
  apps/website/pages/_app.tsx
  apps/website/pages/_document.tsx
  apps/website/pages/index.tsx
  apps/website/public/static/images/avatars/avatar_1.png
  apps/website/public/static/images/avatars/avatar_10.png
  apps/website/public/static/images/avatars/avatar_11.png
  apps/website/public/static/images/avatars/avatar_2.png
  apps/website/public/static/images/avatars/avatar_3.png
  apps/website/public/static/images/avatars/avatar_4.png
  apps/website/public/static/images/avatars/avatar_5.png
  apps/website/public/static/images/avatars/avatar_6.png
  apps/website/public/static/images/avatars/avatar_7.png
  apps/website/public/static/images/avatars/avatar_8.png
  apps/website/public/static/images/avatars/avatar_9.png
  apps/website/public/static/images/products/product_1.png
  apps/website/public/static/images/products/product_2.png
  apps/website/public/static/images/products/product_3.png
  apps/website/public/static/images/products/product_4.png
  apps/website/public/static/images/products/product_5.png
  apps/website/public/static/images/products/product_6.png
  apps/website/public/static/images/sidebar_pro.png
  apps/website/public/static/images/sign-in-illustration.svg
  apps/website/public/static/images/undraw_page_not_found_su7k.svg
  apps/website/public/static/images/undraw_resume_folder_2_arse.svg
  apps/website/public/static/logo.svg
  apps/website/public/static/thumbnail.png
  apps/website/specs/index.spec.tsx
  apps/website/styled.d.ts
  apps/website/svgr.config.js
  apps/website/tsconfig.json
  apps/website/utils/createEmotionCache.ts
  apps/website/with-nx.js
  package.json
  yarn.lock
Labels: enhancement, work_in_progress

#71 added various cool libs from other projects I had
  libs/utils/src/index.ts
  libs/utils/src/lib/anchorifyTextLinks.spec.ts
  libs/utils/src/lib/anchorifyTextLinks.ts
  libs/utils/src/lib/isEmailValid.spec.ts
  libs/utils/src/lib/isEmailValid.ts
  libs/utils/src/lib/newLineToHTMLBR.spec.ts
  libs/utils/src/lib/newLineToHTMLBR.ts
  libs/utils/src/lib/numberFormatter.spec.ts
  libs/utils/src/lib/numberFormatter.ts
  libs/utils/src/lib/playSound.ts
  libs/utils/src/lib/randomNumber.ts
  libs/utils/src/lib/randomString.ts
  libs/utils/src/lib/toInterfacedObjectArray.ts
Labels: enhancement

#86 39 user receives welcome email after registration
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/mailer/mailer.service.ts
  apps/api/src/mailer/templates/welcome.hbs
Labels: work_in_progress
